In [1]:
import numpy as np

test_a = np.array([[4, 8], [2, 9]])
print(test_a * test_a)

[[16 64]
 [ 4 81]]


__2. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__

```
1. [[5 5 5]
    [3 3 3]]
2. [[25 25 25]
    [ 9  9  9]]
3. [[10 10 10]
    [ 6  6  6]]
4. [[75 45]
    [45 27]]
```
> 답 : 2

In [2]:
test_a = np.array([[5, 5, 5], [3, 3, 3]])
print(test_a ** 2)

[[25 25 25]
 [ 9  9  9]]


__3. A = np.array([[3,22,2],[3,1,5]]), B = np.array([[6,7,9],[2,1,3]])일 때, 다음 중 연산이 실행되지 않고 오류가 발생하는 것은?__
1. A * B
2. A.dot(B)
3. A.T.dot(B)
4. A.dot(B.T)

> 답 : 2  
> 행, 열이 같은 행렬끼리는 계산이 되지 않음

In [3]:
A = np.array([[3, 22, 2], [3, 1, 5]])
B = np.array([[6, 7, 9], [2, 1, 3]])

print(A * B)
print(A.T.dot(B))
print(A.dot(B.T))

[[ 18 154  18]
 [  6   1  15]]
[[ 24  24  36]
 [134 155 201]
 [ 22  19  33]]
[[190  34]
 [ 70  22]]


__4. 다음 수식을 나타내는 넘파이 코드를 작성하고자 한다. 다음 코드 중 결과가 다른 것을 하나 찾으시오.__
$$y=\sqrt {\frac{1}{N}\sum_{i=1}^N (y_i-\hat y)}$$

In [4]:
Y_true = np.array([1, 1, 0, 1, 1])
Y_pred = np.array([0.23, 0.5, 0.99, 0.69, 0.4])

```python
1. np.sqrt(np.sum((Y_true - Y_pred)**2) / len(Y_true))
2. diff = (Y_true - Y_pred)
   np.sqrt(diff ** 2 / len(Y_true))
3. np.sqrt(np.sum(np.square((Y_true - Y_pred)))/len(Y_true))
4. diff = (Y_true - Y_pred)
   np.sqrt(diff.T.dot(diff) / len(Y_true))
```
> 답 : 2

In [5]:
print(np.sqrt(np.sum((Y_true - Y_pred) ** 2) / len(Y_true)))

diff = (Y_true - Y_pred)
print(np.sqrt(diff ** 2 / len(Y_true)))

print(np.sqrt(np.sum(np.square((Y_true - Y_pred))) / len(Y_true)))

print(np.sqrt(diff.T.dot(diff) / len(Y_true)))

0.6751444289927897
[0.34435447 0.2236068  0.44274146 0.13863621 0.26832816]
0.6751444289927897
0.6751444289927897


__5. 다음 코드는 ndarray A의 각 원소들을 평균과 표준편차를 이용하여 정규분포로 정규화시키는 벡터 연산 코드이다. 빈칸에 알맞은 것을 고르시오.__
$$\frac{X_i-E(x)}{\sigma}$$

1. sum(axis=1), mean(axis=1)
2. mean(axis=0), std(axis=0)
3. mean, std
4. sum, mean

답 : 3

In [6]:
A = np.array([8, 1, 2, 2, 3, 4, 5, 6, 7, 8])
Z = (A - A.mean(axis=0) / A.std(axis=0))
print(Z)

[ 6.12828654 -0.87171346  0.12828654  0.12828654  1.12828654  2.12828654
  3.12828654  4.12828654  5.12828654  6.12828654]


__6. 다음 수식을 넘파이로 구현하고자 한다. 벡터를 입력하여 정규화된 벡터로 나타낼 때, 수식을 올바른 넘파이 코드로 표현한 것이 아닌 것은 무엇인가?__

$$y_k=exp(a_k)/\sum_{i=1}^n (exp(a_i))$$

```python
1. def softmax(x):
       f_x = x.exp / np.sum(x.exp)
       return f_x
2. def softmax(a) :
       exp_a = np.exp(a)
       sum_exp_a = np.sum(exp_a)
       y = exp_a / sum_exp_a

       return y
3. def softmax(x):
       return np.exp(x) / np.sum(np.exp(x))
4. def softmax(x):
       exponentials = np.exp(x)
       sum_exponentials = sum(exponentials)
       result = exponentials/sum_exponentials
       return result
```

> 답 : 1  
> 1번은 에러 발생

In [7]:
def softmax(x):
    # 1번은 아래와 같이 수정
    f_x = np.exp(x) / np.sum(np.exp(x))
    print(f_x)

    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    print(y)

    print(np.exp(x) / np.sum(np.exp(x)))

    exponentials = np.exp(x)
    sum_exponentials = sum(exponentials)
    result = exponentials / sum_exponentials
    print(result)


softmax([5.0, 2.5, 5.0])

[0.48028779 0.03942442 0.48028779]
[0.48028779 0.03942442 0.48028779]
[0.48028779 0.03942442 0.48028779]
[0.48028779 0.03942442 0.48028779]


__7. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__


1. array([[ 30,  36,  42],
          [ 66,  81,  96],
          [102, 126, 150]])
2. array([[ 5, 14],
          [14, 50]])
3. array([[18, 21, 24],
          [54, 66, 78]])
4. array([[ 8, 26],
          [17, 62],
          [26, 98]])

> 답 : 4

In [8]:
test_a = np.arange(1, 10).reshape(3, 3)
test_b = np.arange(6).reshape(2, 3)

test_a.dot(test_b.T)

array([[ 8, 26],
       [17, 62],
       [26, 98]])

__8. 다음 중 넘파이 배열의 특징으로 적합한 것을 모두 고르시오.__
1. C의 데이터 타입을 기본으로 배열이 생성된다.
2. 동적 타이핑이 지원된다
3. 하나의 데이터 타입만으로 배열이 생성된다.
4. 새로운 데이터를 할당할 때 메모리를 유연하게 사용하여 할당 속도가 빠르다.

> 답 : 1, 3
> 2번 : 배열 연산에 있어 매우 큰 성능적 우위 확보를 위해 동적 타이핑을 포기했다.

__9. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__

1. 4
2. 오류 발생
3. 8
4. 16

> 답 : 3

In [9]:
arr = np.arange(16).reshape(4, 4)
print(arr.size - arr.shape[0] * arr.ndim)

8


__10. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__

1. (10, 2)
2. (2, 10)
3. (5, 4)
4. 오류 발생

> 답 : 2

In [10]:
arr = np.arange(20).reshape(10, 2)
x, y = arr.shape

print(arr.reshape(y, x).shape)

(2, 10)


__11. 다음 배열은 벡터이다. 이 배열을 4×6의 행렬로 바꾸려고 할 때 빈칸에 알맞은 것을 고르시오.__

1. reshape(4, 6) 
2. reshape(-1, 4)
3. flatten(6, 4)
4. flatten( )

> 답 : 1

In [11]:
arr = np.arange(24)
arr = arr.reshape(4, 6)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


__12. 다음 코드를 실행했을 때 결과값이 다른 하나를 고르시오.__

In [12]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

1. arr.flatten()
2. arr.reshape(2, -2)
3. arr.reshape(arr ize)
4. arr

> 답 : 2

In [13]:
print(arr.flatten())
print(arr.reshape(2, -2))
print(arr.reshape(arr.size))
print(arr)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


__13. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__

1. False
2. True
3. array([ True, True, False, False])
4. array([0, 1, 2, 3])

> 답 : 2

In [14]:
arr_1 = np.arange(4)
arr_2 = np.arange(4, 0, -1)

np.any(arr_1 < arr_2)

True

__14. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__

1. array([5])
2. array([0, 1, 2])
3. array([[False, False, False], [False, False, True]])
4. array([3, 4, 5])

답 : 1

In [15]:
a = np.arange(6).reshape(2, 3)
b = a > 4
a[b]

array([5])

__15. 다음 find_nearest_value 함수는 벡터와 어떤 값을 입력하면 해당 벡터 값 중 입력된 값과 차이가 가장 작은 값이 반환된다.__  
__해당 함수로 가장 적합한 코드를 찾으시오.__

```python
1. def find_nearest_value(X, target_value):
       result = X[np.argmax(np.abs(X - target_value))]
       return result
2. def find_nearest_value(X, target_value):
       result = X[np.abs(X - target_value)]
       return result
3. def find_nearest_value(X, target_value):
       result = X[np.argmin(np.abs(X - target_value))]
       return result
4. def find_nearest_value(X, target_value):
       result = X[np.argmax((X - target_value))]
       return result
```

> 답 : 3

In [16]:
def find_nearest_value(X, target_value):
    print(X[np.argmax(np.abs(X - target_value))])
    # print(X[np.abs(X - target_value)]), 값이 정수형이 아니여서 발생
    print(X[np.argmin(np.abs(X - target_value))])
    print(X[np.argmax((X - target_value))])


X = np.array([1, 2, 3, 4, 5, 6, 7])
target_value = 4.3
find_nearest_value(X, target_value)

1
4
7


__16. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__

1. array([6, 6, 6, 4, 7, 9, 1, 8, 8, 4])
2. array([6, 6, 6, 4, 7])
3. array([6, 3, 9, 0, 1])
4. [0 0 6 0 7 9 0 8 8 0]

> 답 : 4

In [17]:
Z = np.array([6, 6, 6, 4, 7, 9, 1, 8, 8, 4])
Z[Z.argsort()[:5]] = 0
print(Z)

[0 0 6 0 7 9 0 8 8 0]


__17. 다음 코드를 실행할 경우 예상되는 결과값은 무엇인가?__

```
1. [[17 27 14 11]
    [11 26 26 23]
    [ 8 24 25 26]]
2. [[17 11  8]
    [27 26 24]
    [14 26 25]
    [11 23 26]]
3. [0, 2, 1] 
4. [[17 27 14 11]
    [ 8 24 25 26]
    [11 26 26 23]]

```

> 답 : 1

In [18]:
arr = np.array([[17, 27, 14, 11],
                [8, 24, 25, 26],
                [11, 26, 26, 23],
                [22, 18, 24, 11]])
print(arr[[0, 2, 1]])

[[17 27 14 11]
 [11 26 26 23]
 [ 8 24 25 26]]
