In [1]:
import numpy as np

test_a = np.array([[4,8],[2,9]])
print(test_a * test_a)

[[16 64]
 [ 4 81]]


In [2]:
test_a = np.array([[5,5,5],[3,3,3]])
print(test_a ** 2)

[[25 25 25]
 [ 9  9  9]]


In [3]:
A = np.array([[3,22,2],[3,1,5]])
B = np.array([[6,7,9],[2,1,3]])

print(A * B)

A.dot(B.T)

print(A.T.dot(B))

[[ 18 154  18]
 [  6   1  15]]
[[ 24  24  36]
 [134 155 201]
 [ 22  19  33]]


#### 다음 수식을 나타내는 넘파이 코드를 작성하고자 한다.
$$y=\sqrt {\frac{1}{N}\sum_{i=1}^N (y_i-\hat y)}$$

In [4]:
Y_true = np.array([1,1,0,1,1])
Y_pred = np.array([0.23,0.5,0.99,0.69,0.4])

print(np.sqrt(np.sum((Y_true - Y_pred)**2) / len(Y_true)))

diff = (Y_true - Y_pred)
print(np.sqrt(diff ** 2 / len(Y_true)))

print(np.sqrt(np.sum(np.square((Y_true - Y_pred)))/len(Y_true)))

print(np.sqrt(diff.T.dot(diff) / len(Y_true)))

0.6751444289927897
[0.34435447 0.2236068  0.44274146 0.13863621 0.26832816]
0.6751444289927897
0.6751444289927897


#### ndarray A의 각 원소들의 평균과 표준편차를 이용하여 정규분포로 정규화시키는 벡터 연산코드이다.
$$\frac{X_i-E(x)}{\sigma}$$

In [5]:
A = np.array([8,1,2,2,3,4,5,6,7,8])
Z = (A - A.mean(axis=0)/A.std(axis=0))
print(Z)

[ 6.12828654 -0.87171346  0.12828654  0.12828654  1.12828654  2.12828654
  3.12828654  4.12828654  5.12828654  6.12828654]


#### 다음 수식을 넘파이로 구현하고자 한다. 벡터를 입력하여 정규화된 벡터로 나타낼 때, 수식을 올바른 넘파이 코드로 표현한 것이 아닌 것은 무엇인가?

$$y_k=exp(a_k)/\sum_{i=1}^n (exp(a_i))$$

In [6]:
def softmax(x):
    
  #  f_x = x.exp / np.sum(x.exp)  print(f_x)
    
    exp_x = np.exp(x)
    sum_exp_x = np.sum(exp_x)
    y = exp_x / sum_exp_x
    y
    
    print(np.exp(x)/np.sum(np.exp(x)))
    
    exponentials = np.exp(x)
    sum_exponentials = sum(exponentials)
    result = exponentials/sum_exponentials
    print(result)
    
softmax([5.0, 2.5, 5.0])

[0.48028779 0.03942442 0.48028779]
[0.48028779 0.03942442 0.48028779]


In [7]:
test_a = np.arange(1,10).reshape(3,3)
test_b = np.arange(6).reshape(2,3)

test_a.dot(test_b.T)

array([[ 8, 26],
       [17, 62],
       [26, 98]])

#### 다음 중 넘파이 배열의 특징으로 적합한 것을 모두 고르시오.
1. C의 데이터 타입을 기본으로 배열이 생성된다.
2. 동적 타이핑이 지원된다 -> 배열 연산에 있어 매우 큰 성능적 우위 확보를 위해 동적 타이핑을 포기했다.
3. 하나의 데이터 타입만으로 배열이 생성된다.
4. 새로운 데이터를 할당할 때 메모리를 유연하게 사용하여 할당 속도가 빠르다. -> X

In [8]:
print("답 : 1, 3")

답 : 1, 3


In [9]:
arr = np.arange(16).reshape(4,4)
print(arr.size - arr.shape[0] * arr.ndim)

8


In [10]:
arr = np.arange(20).reshape(10,2)
x, y = arr.shape

print(arr.reshape(y,x).shape)

(2, 10)


In [11]:
arr = np.arange(24)
arr = arr.reshape(4, 6)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [12]:
arr = np.arange(8)

print(arr.flatten())
print(arr.reshape(2, -2))
print(arr.reshape(arr.size))
print(arr)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [13]:
arr_1 = np.arange(4)
arr_2 = np.arange(4, 0, -1)
                  
np.any(arr_1 < arr_2)

True

In [14]:
a = np.arange(6).reshape(2,3)
b = a > 4
a[b]

array([5])

#### find_nearest_value 함수는 벡터와 어떤 값을 입력하면 해당 벡터 값 중 입력된 값과 차이가 가장 작은 값을 반환한다.

In [15]:
def find_nearest_value(X, target_value):
    result = X[np.argmin(np.abs(X - target_value))]
    return result

X = np.array([1,2,3,4,5,6,7])
target_value = 4.3
print(find_nearest_value(X, target_value))

4


In [16]:
Z = np.array([6,6,6,4,7,9,1,8,8,4])
Z[Z.argsort()[:5]] = 0
print(Z)

[0 0 6 0 7 9 0 8 8 0]


In [17]:
arr = np.array([[17, 27, 14, 11],
               [8, 24, 25, 26],
               [11, 26, 26, 23],
               [22, 18, 24, 11]])
print(arr[[0, 2, 1]])

[[17 27 14 11]
 [11 26 26 23]
 [ 8 24 25 26]]
